name: Test OCI Factory 
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
      - "src/**"
      # - "!.github/workflows/CLA-Check.yaml"
      # - "!.github/workflows/PR-Validator.yaml"
      # - "!.github/workflows/_Auto-updates.yaml"
      # - "!.github/workflows/Continuous-Testing.yaml"
      # - "!.github/workflows/CLI-Client.yaml"
      # - "examples/**"
      # - "oci/mock*"
      # - "!src/workflow-engine/**"
      # - "!src/cli-client/**"


env:
  OCI_FACTORY_REPO: clay-lake/oci-factory # TODO: replace with parent repo when merging back
  OCI_FACTORY_DIR: oci-factory/
  OCI_FACTORY_BRANCH: refactor-workflows
  PYTEST_RESULT_PATH: pytest_results.xml

  # Example working image
  # TEST_IMAGE_NAME: hello-world
  # TEST_IMAGE_TAG: latest

  # Example vulnerable image
  TEST_IMAGE_NAME: mysql
  TEST_IMAGE_TAG: latest

jobs:

  unit-tests:
    # Trigger unit tests across the repository
    name: Unit Tests
    runs-on: ubuntu-22.04
    # TODO: Iterate over testable directories with matrix
    steps:

      # Job Setup
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.OCI_FACTORY_REPO }}
          path: ${{ env.OCI_FACTORY_DIR }}
          ref: ${{ env.OCI_FACTORY_BRANCH }}
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      # Unit Test requirements
      - run: pip install -r ${{ env.OCI_FACTORY_DIR }}/src/test-oci-factory/unit-tests/requirements.txt
      # build-rock configure requirements 
      - run: pip install -r ${{ env.OCI_FACTORY_DIR }}/src/build-rock/configure/requirements.txt


      - name: Run pytest
        continue-on-error: true
        run: |
          python3 -m pytest --junit-xml "${{ env.PYTEST_RESULT_PATH }}" "${{ env.OCI_FACTORY_DIR }}" || true
          python3 ${{ env.OCI_FACTORY_DIR }}/src/test-oci-factory/unit-tests/junit_to_markdown.py \
            --input-junit "${{ env.PYTEST_RESULT_PATH }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload pytest Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PYTEST_RESULT_PATH }}
          path: ${{ env.PYTEST_RESULT_PATH }}
          if-no-files-found: error




  integration-test-build-rock:
    # Test the Build-Rock workflow by calling a build with the mock-rock
    name: Integration Test - Build-Rock
    uses: ./.github/workflows/Build-Rock.yaml
    with:
      oci-archive-name: "mock-rock_1.1.rock"
      rock-repo: canonical/oci-factory
      # TODO replace commit below with 'main' once changes have been merged back
      rock-repo-commit: 7f080b50ba656538aee3819889090c173f06debd
      rockfile-directory: examples/mock-rock/1.1/
    

  setup-test-rock:
    name: Setup - Test-Rock
    runs-on: ubuntu-22.04
    outputs: 
        oci-archive-name: ${{ steps.configure.outputs.oci-archive-name }}
    steps:
      
      - name: Configure
        id: configure
        run: |
          echo "oci-archive-name=${{env.TEST_IMAGE_NAME}}_${{ env.TEST_IMAGE_TAG }}.rock"  >> $GITHUB_OUTPUT

      - name: Download Test Image from DockerHub
        run: |
          docker pull ${{env.TEST_IMAGE_NAME}}:${{ env.TEST_IMAGE_TAG }}
          docker save ${{env.TEST_IMAGE_NAME}}:${{ env.TEST_IMAGE_TAG }} > ${{ steps.configure.outputs.oci-archive-name }}

      - name: Upload Test Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.configure.outputs.oci-archive-name }}
          path: ${{ steps.configure.outputs.oci-archive-name }}
          if-no-files-found: error


  integration-test-test-rock:
    # Test the Build-Rock workflow by calling a build with the mock-rock
    name: Integration Test - Test-Rock
    needs: [setup-test-rock]
    uses: ./.github/workflows/Test-Rock.yaml
    with:
      oci-archive-name: ${{ needs.setup-test-rock.outputs.oci-archive-name }}

