name: _Test OCI Factory | mock-rock
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
      # - "!.github/workflows/CLA-Check.yaml"
      # - "!.github/workflows/PR-Validator.yaml"
      # - "!.github/workflows/_Auto-updates.yaml"
      # - "!.github/workflows/Continuous-Testing.yaml"
      # - "!.github/workflows/CLI-Client.yaml"
      # - "examples/**"
      # - "oci/mock*"
      # - "src/**"
      # - "!src/workflow-engine/**"
      # - "!src/cli-client/**"

jobs:
  # test-workflows:
  #   name: Trigger internal tests for mock-rock
  #   uses: ./.github/workflows/Image.yaml
  #   with:
  #     oci-image-name: "mock-rock"
  #     upload: true
  #   secrets: inherit

  test-build-rock:
    name: Test Build Workflow  
    uses: ./.github/workflows/Build-Rock.yaml
    with:
      oci-archive-name: "mock-rock_1.1.rock"
      rock-repo: canonical/oci-factory
      rock-repo-commit: 7f080b50ba656538aee3819889090c173f06debd
      rockfile-directory: examples/mock-rock/1.1/
