name: _Test OCI Factory | mock-rock
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
      - "!.github/workflows/CLA-Check.yaml"
      - "!.github/workflows/PR-Validator.yaml"
      - "!.github/workflows/_Auto-updates.yaml"
      - "!.github/workflows/Continuous-Testing.yaml"
      - "!.github/workflows/CLI-Client.yaml"
      - "examples/**"
      - "oci/mock*"
      - "src/**"
      - "!src/workflow-engine/**"
      - "!src/cli-client/**"

jobs:
  test-workflows:
    name: Trigger internal tests for mock-rock
    uses: ./.github/workflows/Image.yaml
    with:
      oci-image-name: "mock-rock"
      upload: true
    secrets: inherit

  test-oci-factory:
    runs-on: ubuntu-22.04
    steps:
      - name: execute bash
        run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/ORG/actions/runners