name: Build-Rock Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      rock-repo:
        description: "Public Git repo where to build the rock from"
        type: string
        required: true
      rock-repo-commit:
        description: "Git ref from where to build the rock from"
        type: string
        default: HEAD
        required: false
      rockfile-directory:
        description: "Directory, in 'rock-repo', where to find the rockcraft.yaml file"
        type: string
        required: true

# env:
#   # TODO: establish build directory?
#   ROCK_REPO_DIR: rock-repo
#   ROCKS_CI_FOLDER: ci-rocks

jobs:
  prepare-multi-arch-matrix:
    runs-on: ubuntu-22.04
    steps:

      - name: Execute Build
        uses: ./.github/workflows/Build-Rock.yaml
        with:
          oci-archive-name: "Test"
          rock-repo: ${{ inputs.rock-repo }}
          rock-repo-commit: ${{ inputs.rock-repo-commit }}
          rockfile-directory: ${{ inputs.rockfile-directory }}
    

      # setup
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4.44.3
      - uses: actions/setup-python@v5
