name: Scan Rock Vulnerabilities

on:
  workflow_call:
    inputs:
      oci-archive-name:
        description: 'OCI image artifact name'
        required: true
        type: string
      oci-image-path:
        description: 'Path to the image in this repo (eg. "oci/foo")'
        required: true
        type: string
      vulnerability-report-suffix:
        description: 'Suffix for the vulnerability report artefact'
        required: false
        type: string
        default: '.vulnerability-report.json'
      date-last-scan:
        description: 'If there are new CVEs after this date, we notify'
        required: false
        type: string
        default: '9999-12-31T23:59:59'

env:
  OCI_FACTORY_REPO: clay-lake/oci-factory # TODO: replace with parent repo when merging back
  OCI_FACTORY_DIR: oci-factory/
  OCI_FACTORY_BRANCH: refactor-workflows

  TEST_IMAGE_NAME: 'test-img'
  TEST_IMAGE_TAG: 'test'
  SKOPEO_IMAGE: 'quay.io/skopeo/stable:v1.15.1'

jobs:
  test-vulnerabilities:
    runs-on: ubuntu-22.04
    name: Vulnerability scan
    outputs:
      vulnerability-report: ${{ steps.vulnerability-report.outputs.name }}
      notify: ${{ steps.check-report.outputs.notify }}
    steps:
      # Job Setup
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.OCI_FACTORY_REPO }}
          path: ${{ env.OCI_FACTORY_DIR }}
          ref: ${{ env.OCI_FACTORY_BRANCH }}
          fetch-depth: 1


      - name: Download Test Image
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.oci-archive-name }}

      - id: Configure
        run: |
          full_name="${{ inputs.oci-image-name }}${{ inputs.vulnerability-report-suffix }}"
          final_name="$(echo ${full_name} | sed 's/ghcr.io\/canonical\/oci-factory\///g' | tr ':' '_')"
          echo "name=$final_name" >> "$GITHUB_OUTPUT" 
      
      # Note: removed to allow common interface using only artifacts
      # - name: Copy image to Docker daemon
      #   id: to-docker-daemon
      #   run: |
      #     d_img_name="${{ env.TEST_IMAGE_NAME}}:${{ env.TEST_IMAGE_TAG }}"
      #     echo "name=$d_img_name" >> "$GITHUB_OUTPUT"
      #       source=docker://${{ inputs.oci-image-name }}
      #     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      #       -v $PWD:/workdir -w /workdir \
      #       ${{ env.SKOPEO_IMAGE }} \
      #       copy $source \
      #       docker-daemon:$d_img_name

      - name: Copy image to Docker daemon
        run: |
          ls -R
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workdir -w /workdir \
            ${{ env.SKOPEO_IMAGE }} \
            copy oci-archive:${{ inputs.oci-archive-name }} \
            docker-daemon:${{ env.TEST_IMAGE_NAME}}:${{ env.TEST_IMAGE_TAG }}

      - name: Check for .trivyignore
        id: trivyignore
        run: |
          if [ -f ${{ inputs.oci-image-path }}/.trivyignore ]
          then
            file=${{ inputs.oci-image-path }}/.trivyignore
          else
            # dummy .trivyignore file
            file=.trivyignore
            touch $file
          fi
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@0.9.2
        with:
          # NOTE: we're allowing images with vulnerabilities to be published
          ignore-unfixed: true
          trivyignores: ${{ steps.trivyignore.outputs.file }}
          format: 'cosign-vuln'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          # NOTE: pebble is flagged with a HIGH vuln because of golang.org/x/crypto
          # CVE-2021-43565, CVE-2022-27191
          skip-files: /bin/pebble
          # missing ${{ runner.arch }}
          output: '${{ steps.vulnerability-report.outputs.name }}'
          image-ref: '${{ steps.to-docker-daemon.outputs.name }}'

      - name: Process report
        if: ${{ always() }}
        id: check-report
        run: |
          report="${{ steps.vulnerability-report.outputs.name }}"
          cat $report
          echo "notify=false" >> "$GITHUB_OUTPUT"
          set -x
          last_modified_dates="$(jq -r 'try(.scanner.result.Results[].Vulnerabilities)
                  | select(. != null) 
                  | .[].LastModifiedDate
                  | select(. != null)' < $report)"

          # We want to notify only if the CVEs have been updated since the last
          # time this scan ran
          for cve_updated in $last_modified_dates
          do
            if [[ "$cve_updated" > "${{ inputs.date-last-scan }}" ]]
            then
              echo "notify=true" >> "$GITHUB_OUTPUT"
              break
            fi
          done

      - uses: actions/cache/save@v4
        if: ${{ always() }}
        with:
          path: ${{ steps.vulnerability-report.outputs.name }}
          key: ${{ github.run_id }}-${{ steps.vulnerability-report.outputs.name }}

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ steps.vulnerability-report.outputs.name }}
          path: ${{ steps.vulnerability-report.outputs.name }}


  # # Many workflows are now using a similar notification job. It would be better
  # # if this was a common workflows reachable via a workflow_call
  # notify:
  #   runs-on: ubuntu-22.04
  #   name: Notify on failure
  #   needs:
  #     - test-vulnerabilities
  #   if: ${{ always() && needs.test-vulnerabilities.outputs.notify == 'true' }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'

  #     - name: Get contacts for ${{ inputs.oci-image-name }}
  #       id: get-contacts
  #       working-directory: ${{ inputs.oci-image-path }}
  #       run: |
  #         mm_channels=$(yq -r '.notify | ."mattermost-channels" | join(",")' < contacts.y*ml)
  #         echo "mattermost-channels=${mm_channels}" >> "$GITHUB_OUTPUT"

  #     - name: Notify via Mattermost
  #       env:
  #         MM_BOT_TOKEN: ${{ secrets.MM_BOT_TOKEN }}
  #         FINAL_STATUS: failure
  #         MM_SERVER: ${{ secrets.MM_SERVER }}
  #         URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  #         SUMMARY: ''
  #         FOOTER: ''
  #         TITLE: 'CVEs found for ${{ inputs.oci-image-name }}'
  #       run: |
  #         for channel in $(echo ${{ steps.get-contacts.outputs.mattermost-channels }} | tr ',' ' ')
  #         do
  #           MM_CHANNEL_ID="${channel}" ./src/notifications/send_to_mattermost.sh
  #         done
